#:import hex kivy.utils.get_color_from_hex

<TextoOscuro@Label>
    color: hex('#252525')

#Login
<LoginRoot>:
    orientation: 'vertical'

    canvas.before:
        Color:
            rgba: hex('#ECF0EF')
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation:'vertical'
        size_hint_y: 1
        TextoOscuro:
            text:'Hola mundo'
